# Generated by Django 5.1.6 on 2025-03-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_category_cake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
